#!/usr/bin/env bash

bbl --aws-access-key-id="${AWS_KEY_ID}" \
  --aws-secret-access-key="${SECRET_ACCESS_KEY}" \
  --aws-region=us-east-1 \
  unsupported-deploy-bosh-on-aws-for-concourse \
  --lb-type=none | tee bbl.log

