#!/usr/bin/env bash

set +e

SCRIPT_DIR="$(dirname $0)"
RELEASE_DIR="${RELEASE_DIR:-$SCRIPT_DIR/..}"
DEPLOYMENTS_DIR="${RELEASE_DIR}/deployments"

mkdir -p "${RELEASE_DIR}/deployments"

${RELEASE_DIR}/scripts/generate-manifest \
 > "${DEPLOYMENTS_DIR}/deploy.yml"

sed -i '' "s/AWS_KEY_ID/${AWS_KEY_ID}/g" "${DEPLOYMENTS_DIR}/deploy.yml"
sed -i '' "s/SECRET_ACCESS_KEY/${SECRET_ACCESS_KEY}/g" "${DEPLOYMENTS_DIR}/deploy.yml"

bosh cloud-config > "${DEPLOYMENTS_DIR}/bbl-cloud-config.yml"

sed -i '' 's/vm_types:/vm_types:\
- <<: (( merge ))/g' "${DEPLOYMENTS_DIR}/bbl-cloud-config.yml"

${RELEASE_DIR}/scripts/generate-cloud-config \
 > "${RELEASE_DIR}/deployments/cloud.yml"

bosh update cloud-config deployments/cloud.yml
bosh deployment "${DEPLOYMENTS_DIR}/deploy.yml"

bosh --parallel 10 sync blobs
bosh create release --name blobstore-perf --force
bosh -n upload release
bosh -d ${RELEASE_DIR}/deployments/deploy.yml -n deploy
